### ISSUE TITLE
Paste and multiline input

### ISSUE THREAD

**Issue by mancvso** [skerit/janeway#9]
Whenever I try to write a function on the REPL o paste one, I get it interpreted line by line instead of allowing me to keep giving input.

For example, this function will be evaluated line by line.

```js
function anexar_attrs(el){
  let fecha_embarque = MomentTimezone(el.fecha_embarque).tz("America/Santiago")
  let hora_embarque = fecha_embarque.format("HH:mm:ss")
  let dia_embarque = fecha_embarque.format("YY-MM-d")
  return {
    codigo_ticket: el.codigo_ticket,
    dia_embarque: dia_embarque,
    hora_embarque: hora_embarque,
    tipo: el.tipo,
    nave: el.nave
  }
}
```

**Comment by skerit** [comment]
Yeah, that can be quite annoying. I'll look into it!

**Comment by skerit** [comment]
Janeway should detect multiline pastes from now on.

When you paste something the terminal just interprets it as if you're typing on the keyboard. But it types rather fast, so when an enter happens too fast (less than 24ms since the last key) it'll just append the string to the input area from now on.

Now about typing multiline strings into the input area directly:

1. There is no way to detect a `ctrl` or `shift` when pressing enter, so I can't configure it to just add a newline when pressing `shift+enter`, for example
2. Even if it could, the `Editarea` class I'm using really, really hates scrolling. (Most of the `blessed` inputs do, actually.) Everything breaks horribly
